import type { Metadata } from "next";
import localFont from "next/font/local";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const magicRetro = localFont({
  src: [
    {
      path: "../public/fonts/Magic Retro.ttf",
    },
  ],
  variable: "--font-magic-retro",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${magicRetro.className} ${montserrat.className} 'p-0 m-0 '`}
      >
        {children}
      </body>
    </html>
  );
}
